#ifndef KERN_KEYBOARD_H
#define KERN_KEYBOARD_H

#include <Uefi.h>

#include <Library/UefiLib.h>

/**
    Enum of key press down codes. 
 **/
enum PS2_KEYS {
  ESCAPE          = 0x01,
  INT_ONE         = 0x02,
  INT_TWO         = 0x03,
  INT_THREE       = 0x04,
  INT_FOUR        = 0x05,
  INT_FIVE        = 0x06,
  INT_SIX         = 0x07,
  INT_SEVEN       = 0x08,
  INT_EIGHT       = 0x09,
  INT_NINE        = 0x0A,
  INT_ZERO        = 0x0B,
  DASH            = 0x0C,
  EQUALS          = 0x0D,
  BACKSPACE       = 0x0E,
  TAB             = 0x0F,
  Q               = 0x10,
  W               = 0x11,
  E               = 0x12,
  R               = 0x13,
  T               = 0x14,
  Y               = 0x15,
  U               = 0x16,
  I               = 0x17,
  O               = 0x18,
  P               = 0x19,
  LBRACKET        = 0x1A,
  RBRACKET        = 0x1B,
  ENTER           = 0x1C,
  LCTRL           = 0x1D,
  A               = 0x1E,
  S               = 0x1F,
  D               = 0x20,
  F               = 0x21,
  G               = 0x22,
  H               = 0x23,
  J               = 0x24,
  K               = 0x25,
  L               = 0x26,
  SEMICLN         = 0x27,
  SINGLEQT        = 0x28,
  BACKTICK        = 0x29,
  LSHIFT          = 0x2A,
  BSLASH          = 0x2B,
  Z               = 0x2C,
  X               = 0x2D,
  C               = 0x2E,
  V               = 0x2F,
  B               = 0x30,
  N               = 0x31,
  M               = 0x32,
  COMMA           = 0x33,
  DOT             = 0x34,
  FWDSLASH        = 0x35,
  RSHIFT          = 0x36,
  NUMPAD_ASTERISK = 0x37,
  LALT            = 0x38,
  SPACE           = 0x39,
  CAPS_LOCK       = 0x3A,
} KEY_PRESS_DOWN;

/**
    Enum of key release codes. 
 **/
enum PS2_KEYS {
  ESCAPE          = 0x81,
  INT_ONE         = 0x82,
  INT_TWO         = 0x83,
  INT_THREE       = 0x84,
  INT_FOUR        = 0x85,
  INT_FIVE        = 0x86,
  INT_SIX         = 0x87,
  INT_SEVEN       = 0x88,
  INT_EIGHT       = 0x89,
  INT_NINE        = 0x8A,
  INT_ZERO        = 0x8B,
  DASH            = 0x8C,
  EQUALS          = 0x8D,
  BACKSPACE       = 0x8E,
  TAB             = 0x8F,
  Q               = 0x90,
  W               = 0x91,
  E               = 0x92,
  R               = 0x93,
  T               = 0x94,
  Y               = 0x95,
  U               = 0x96,
  I               = 0x97,
  O               = 0x98,
  P               = 0x99,
  LBRACKET        = 0x9A,
  RBRACKET        = 0x9B,
  ENTER           = 0x9C,
  LCTRL           = 0x9D,
  A               = 0x9E,
  S               = 0x9F,
  D               = 0xA0,
  F               = 0xA1,
  G               = 0xA2,
  H               = 0xA3,
  J               = 0xA4,
  K               = 0xA5,
  L               = 0xA6,
  SEMICLN         = 0xA7,
  SINGLEQT        = 0xA8,
  BACKTICK        = 0xA9,
  LSHIFT          = 0xAA,
  BSLASH          = 0xAB,
  Z               = 0xAC,
  X               = 0xAD,
  C               = 0xAE,
  V               = 0xAF,
  B               = 0xB0,
  N               = 0xB1,
  M               = 0xB2,
  COMMA           = 0xB3,
  DOT             = 0xB4,
  FWDSLASH        = 0xB5,
  RSHIFT          = 0xB6,
  NUMPAD_ASTERISK = 0xB7,
  LALT            = 0xB8,
  SPACE           = 0xB9,
  CAPS_LOCK       = 0xBA,
} KEY_RELEASE;

#endif /* KernKeyboard.h */
