#ifndef TRAPEXCEPTIONS_H
#define TRAPEXCEPTIONS_H

enum TrapExceptions {
  DIVISION_ERROR,
  DEBUG,
  NON_MASKABLE_INT,
  BREAKPOINT,
  OVERFLOW,
  BOUND_RANGE_EXCEEDED,
  INVALID_OPCODE,
  DEV_NOT_AVAIL,
  DOUBLE_FAULT,
  COPROC_SEG_OVERRUN,
  INVALID_TSS,
  SEG_NOT_PRESENT,
  STACK_SEG_FAULT,
  GEN_PROTECT_FAULT,
  PAGE_FAULT,
  RESERVED1,
  X87_FLOATING_POINT_EXC,
  ALIGNMENT_CHECK,
  MACHINE_CHECK,
  SIMD_FP_EXC,
  VIRT_EXC,
  CTRL_PROTECT_EXC,
  RESERVED2,
  HYPERV_INJECT_EXC,
  VMM_COMMS_EXC,
  SECURITY_EXC,
  RESERVED3,
  TRIPLE_FAULT,
  FPU_ERR_INT
};

#endif /* TrapExceptions.h */
